### PR TITLE
changing because pyhaversion has been rewriting

### PR DESCRIPTION
**Pull request by maheus**
after lot of changes in pyhaversion repository , breaking changes is on error in HA (issue #36)
```
Failed config
  General Errors: 
    - Component error: breaking_changes - cannot import name 'LocalVersion' from 'pyhaversion' (/usr/local/lib/python3.8/site-packages/pyhaversion/__init__.py)
```

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]

**Comment by ludeeus** [comment]
This will break integrations in HA core.
It is correct and should be merged, but I do not want to do that until HA core has been updated.

Changing `pyhaversion>=3.1.0` to `pyhaversion>=3.1.0,<=3.4.2` could be released as a hotfix

**Comment by maheus** [comment]
no problem @ludeeus , do you will push the hotfix or do you want that i'm doing it?

**Comment by ludeeus** [comment]
If you do it, I can probably release it today/tomorrow (UTC), If I do it, it will be later :smile:

**Comment by maheus** [comment]
;) 
ok

**Pull request closed without merging**
